---
- name: Manage Docker containers
  hosts: 54.85.26.230
  become: yes
  gather_facts: false
  tasks:
    
    # Step 1: Get list of running containers
    - name: Get list of running containers
      command: docker ps -q
      register: running_containers
      changed_when: false

    # Step 2: Debug the list of running containers (optional)
    - name: Debug list of running containers
      debug:
        var: running_containers.stdout_lines

    # Step 3: Stop and remove each running container
    - name: Stop and remove running containers
      docker_container:
        name: "{{ item }}"
        state: "absent"
      loop: "{{ running_containers.stdout_lines }}"
      when: running_containers.stdout_lines | length > 0

    - name: Start Docker Container
      community.docker.docker_container:
        name: node-app
        image: krishnachennaidocker/node-app-image:jenkins-1
        state: started
        published_ports:
          - "3000:3000"  # Ensure published_ports is a list

    # Step 5: Debug to verify the started container (optional)
    - name: Debug latest container started
      debug:
        var: latest_container
