---
- name: Docker Deployment Starting...
  hosts: 54.85.26.230
  become: yes
  gather_facts: yes
  tasks: 
    - name: Gather the existing images
      community.docker.docker_image:
        #state: present
        name: krishnachennaidocker/node-app-image:jenkins-1
      register: docker_images
      
    - name: Show gathered Docker images
      debug:
        var: docker_images.images
        
    - name: Remove Docker image
      community.docker.docker_image:
        name: "{{ item.RepoTags[0] }}"
        state: absent
      loop: "{{ docker_images.images }}"
      when: "'ubuntu' in item.RepoTags[0]"
      
#    - name: Show Removed Image
#      debug:
#        var: result
        
    - name: Get the existing information of node-app container
      community.docker.docker_container_info:
        name: node-app
      register: result.images
      
    - name: Does container exist?
      debug:
        msg: The container {{ 'exists' if result.exists else 'does not exist' }}
      when: result.exists
      
    - name: Stop a container
      community.docker.docker_container:
        name: node-app
        state: stopped
      when: result.exists
      
    - name: Remove container
      community.docker.docker_container:
        name: node-app
        state: absent
      when: result.exists
      
    - name: Pull Image and Start Docker Container
      community.docker.docker_container:
        name: node-app
        image: krishnachennaidocker/node-app-image:jenkins-1
        state: started
        published_ports:
          - 3000:3000
          
    - name: Debug latest container started
      debug:
        var: latest_container
