---
- hosts: 54.85.26.230
  become: yes
  gather_facts: false
  tasks:
  
    - name: Pull Docker image
      docker_image:
        name: krishnachennaidocker/node-app-image
        source: pull
        tag: jenkins-1

    - name: Get the container ID of the node-app container
      community.docker.docker_ps:
        name: node-app  # Filter by container name
        format: '{{ id }}'  # Only fetch the container ID
      register: container_info
      failed_when: container_info.stdout == ""  # Fail if no container is found

    - name: Stop the container
      docker_container:
        name: "{{ container_info.stdout }}"
        state: stopped
      when: container_info.stdout != ""  # Only stop if the container exists

    - name: Remove the container
      docker_container:
        name: "{{ container_info.stdout }}"
        state: absent
      when: container_info.stdout != ""  # Only remove if the container exists

    - name: Start Docker Container
      docker_container:
        name: node-app
        image: krishnachennaidocker/node-app-image:jenkins-1
        state: started
        published_ports:
          - "3000:3000"  # Ensure published_ports is a list

    - name: Get the Container info
      community.docker.docker_container_info:
        name: node-app
      register: result
      
    - name: Does Container exist..?
      debug:
        msg: "The node-app container is {{ 'exists' if result.containers else 'does not exist' }}"
      when: result.containers is defined

    - name: Print the Container information
      debug:
        var: result.containers
      when: result.containers  # Only print if container exists
