---
- hosts: 54.85.26.230
  become: yes
  gather_facts: false
  tasks:

    - name: Pull Docker image
      docker_image:
        name: krishnachennaidocker/node-app-image
        source: pull
        tag: jenkins-1

    - name: Start Docker Container
      docker_container:
        name: node-app
        image: krishnachennaidocker/node-app-image:jenkins-1
        state: started
        published_ports:
          - "3000:3000"  # Ensure published_ports is a list

    - name: Get the Container info
      community.docker.docker_container_info:
        name: node-app  # Added space for correct YAML syntax
      register: result

    - name: Does Container exist..?
      debug:
        msg: "The node-app container is {{ 'exists' if result.containers else 'does not exist'}}"  # Fix logic for checking container existence

    - name: Print the Container information
      debug:
        var: result.containers
      when: result.containers  # Checking if the container information exists
